### PR TITLE
fixes a couple of bugs with sharding;

### PR DESCRIPTION
**Pull request by ctcac00**
hi @pkdone, I've fixed a couple of bugs with the sharding  - sorry about all the changes - that's my auto formatter kicking in...

### CODE REVIEW

**Comment by pkdone** [comment]
Hi mate as per slack can you re-submit using the project's existing style based on PEP 8 but with max line width = 100
eg. _alias pycodestyle='pycodestyle --max-line-length=100'_

**Comment by ctcac00** [comment]
ok, this should be better now

**Comment by pkdone** [comment]
I don't understand the first change (removal of "$") and how it is working for you. Agg Fwk $type operator when provided a field path as the expression for its argument expects a "$" prefix to the field name.

See example from: https://docs.mongodb.com/manual/reference/operator/aggregation/type/
```
db.coll.aggregate([{
    $project: {
       a : { $type: "$a" }
    }
}])
```
Can you double check please?

**Comment by ctcac00** [comment]
I'm using MongoDB 5.0.3
image

it also works with the $ sign:
image

but for some reason it fails on the python script:
image

then if I change it:
image

works as expected

**Comment by pkdone** [comment]
Hi Carlos. I'm still struggling to reproduce. I was using 5.0.2 locally but just upgraded to 5.0.5 and I have no change in behaviour I see for the agg pipeline for either mongos or pymongo.

Is your "card_number" field a string field? In which case running $type on a constant "card_number" will of course return a string because it is NOT returning the type of the card_number field, it is returning the type of the string constant "card_number". I tested on sample_mflix.movies for fields title and year with and without $ prefix. With prefix, it returns string for "$titlte" and returns int for "$year". Without the $ prefix it always returns string because it isn't testing a field, it's looking at a string constant. Therefore you must always use $ prefix for $type to reference a field in a document. 

I then built a very small test Python client to see if there is something specific to use of pymongo going on but again I saw behavior expected for both "$title" and "$year". 

Here's my python test code which should be put into a file called **gettype.py**, made executable and then run:

```
#!/usr/bin/python3
from pymongo import MongoClient
from pprint import pprint

connection = MongoClient("mongodb://localhost:27017")
db = connection["sample_mflix"]
field = "year"  # try: "title" (string) and "year" (int)

pipeline = [
    {"$limit": 1},
    {"$project": {
        "_id": 0,
        "type": {"$type": f"${field}"},
    }},
]

firstRecord = db["movies"].aggregate(pipeline).next()
pprint(firstRecord)
```

Can you do me a favour and try this python client in your env for both a text field and then for a number field and see what happens?
Thanks
Paul

**Comment by ctcac00** [comment]
Hi Paul,
it works fine for both:
image

Let's leave the PR for now and I'll show you when we're back next year!

**Comment by pkdone** [comment]
Ok thanks yep let's catch up then. IN meantime I will make the other correction directly to main - thanks for that

**Comment by pkdone** [comment]
As discussed the fix is more substantial which I am making to the code separately from this pull request. Thanks for catching the issue!

**Pull request closed without merging**
